pybo/urls.py
from django.urls import path
from .views import base_views, question_views, answer_views, comment_views, vote_views

app_name = 'pybo'

urlpatterns = [
    #base_views.py
    path('', base_views.index, name='index'),
    path('<int:question_id>/', base_views.detail, name='detail'),

    #question_views.py
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),

    #answer_views.py
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),

    #comment_views.py
    path('comment/create/question/<int:question_id>/', comment_views.comment_create_que, name='comment_create_que'),
    path('comment/modify/question/<int:comment_id>/', comment_views.comment_modify_que, name='comment_modify_que'),
    path('comment/delete/question/<int:comment_id>/', comment_views.comment_delete_que, name='comment_delete_que'),
    path('comment/create/answer/<int:answer_id>/', comment_views.comment_create_ans, name='comment_create_ans'),
    path('comment/modify/answer/<int:comment_id>/', comment_views.comment_modify_ans, name='comment_modify_ans'),
    path('comment/delete/answer/<int:comment_id>/', comment_views.comment_delete_ans, name='comment_delete_ans'),

    #vote_views.py
    path('vote/question/<int:question_id>/', vote_views.vote_question, name='vote_question'),
    path('vote/answer/<int:answer_id>/', vote_views.vote_answer, name='vote_answer'),
]

pybo/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

#게시글 카테고리
class Category(models.Model):
    cname = models.CharField(max_length=100)
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)

#게시글 질문하기
class Question(models.Model):
    cate = models.ForeignKey(Category, on_delete=models.DO_NOTHING)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question')
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_question')
    cnt = models.IntegerField(default=0)

    def __str__(self):
        return self.subject


#게시글 답변하기
class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_answer')
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_answer')

#댓글
class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    question = models.ForeignKey(Question, null=True, blank=True, on_delete=models.CASCADE)
    answer = models.ForeignKey(Answer, null=True, blank=True, on_delete=models.CASCADE)

pybo/forms.py
from django import forms
from pybo.models import Question, Answer, Comment

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['cate','subject', 'content']
        labels = {
            'cate': '분류',
            'subject':'제목',
            'content':'내용',
        }

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content':'답변내용',
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        labels = {
            'content':'댓글내용',
        }

pybo/views/answer_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone

from ..forms import AnswerForm
from ..models import Question, Answer


@login_required(login_url='common:login')
def answer_create(request, question_id):
    """
    pybo 답변등록
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user #현재 로그인 User 모델의 객체
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            #return redirect('pybo:detail', question_id=question.id)
            return redirect('{}#answer_{}'.format(resolve_url('pybo:detail',question_id=question.id),answer.id))
    else:
        form = AnswerForm()

    context = {'question':question, 'form':form}
    return render(request,'pybo/question_detail.html', context)

@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    """
    pybo 답변 수정
    """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '수정권한이 없습니다.')
        return redirect('pybo:detail', question_id=answer.question.id)

    if request.method == 'POST':
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.modify_date = timezone.now()
            answer.save()
            #return redirect('pybo:detail',question_id=answer.question.id)
            return redirect('{}#answer_{}'.format(resolve_url('pybo:detail', question_id=answer.question.id), answer.id))
    else:
        form = AnswerForm(instance=answer)
    context = {'answer': answer, 'form':form}
    return render(request, 'pybo/answer_form.html', context)

@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    """
    pybo 답변 삭제
    """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '삭제권한이 없습니다.')
    else:
        answer.delete()
    return redirect('pybo:detail', question_id=answer.question.id)

pybo/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.db.models import Q, Count
from ..models import Category,Question,Answer,Comment

import logging
logger = logging.getLogger('pybo')

def index(request):
    """
    pybo 질문 목록 출력
    """

    logger.info("INFO 레벨로 출력")

    #최근 답변 5개
    new_answer = Answer.objects.order_by('id')[:5]

    #최근 댓글 5개
    new_comment = Comment.objects.order_by('id')[:5]

    page = request.GET.get('page','1')
    kw = request.GET.get('kw','')
    so = request.GET.get('so', 'recent')
    ca = request.GET.get('ca', '')

    categorys = Category.objects.order_by('-id')

    if not ca:
        question_list = Question.objects.select_related('cate').filter(cate_id=1)
        ca = 1
    elif ca == 'all':
        question_list = Question.objects.select_related('cate')
    else:
        question_list =  Question.objects.select_related('cate').filter(cate_id=ca)

    if so == 'recommend':
        question_list = question_list.annotate(num_voter=Count('voter')).order_by('-num_voter','-id')
    elif so == 'popular':
        question_list = question_list.annotate(num_answer=Count('answer')).order_by('-num_answer','-id')
    else: #recent
        question_list = question_list.order_by('-id')

    if kw: #검색키워드
        question_list = question_list.filter(
            Q(subject__icontains=kw) |
            Q(content__icontains=kw) |
            Q(author__username__icontains=kw) |
            Q(answer__author__username__icontains=kw)
        ).distinct()

    import math

    paginator = Paginator(question_list,10)
    page_obj = paginator.get_page(page)
    page_obj.e_number = math.ceil(page_obj.paginator.count / page_obj.paginator.per_page)

    context = {'question_list': page_obj, 'page': page, 'kw': kw, 'so': so, 'ca':ca, 'cate_list':categorys,'new_answer':new_answer,'new_comment':new_comment}
    return render(request, 'pybo/question_list.html', context)

def detail(request, question_id):
    """
    pybo 질문 내용출력
    """
    page = request.GET.get('page', '1')
    so = request.GET.get('so', 'recent')

    question = get_object_or_404(Question, pk=question_id)

    # 조회수 증가
    view_cnt = 'view_count(%d)'%question.id
    if view_cnt not in request.session._session:
        request.session[view_cnt] = True
        question.cnt = question.cnt + 1
        question.save()

    if so == 'recommend':
        answer = Answer.objects.filter(question_id=question_id).annotate(num_voter=Count('voter')).order_by('-num_voter','-id')
    else: #recent
        answer = Answer.objects.filter(question_id=question_id).order_by('-id')

    import math

    paginator = Paginator(answer,3)
    page_obj = paginator.get_page(page)
    page_obj.e_number = math.ceil(page_obj.paginator.count / page_obj.paginator.per_page)

    context = {'question': question,'answer_list': page_obj, 'page': page, 'so': so}
    return render(request, 'pybo/question_detail.html', context)

pybo/views/comment_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone

from ..forms import CommentForm
from ..models import Question, Answer, Comment


@login_required(login_url='common:login')
def comment_create_que(request, question_id):
    """
    pybo 질문에 대한 댓글 등록
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user #현재 로그인 User 모델의 객체
            comment.create_date = timezone.now()
            comment.question = question
            comment.save()
            #return redirect('pybo:detail', question_id=question.id)
            return redirect('{}#comment_{}'.format(resolve_url('pybo:detail', question_id=comment.question.id), comment.id))
    else:
        form = CommentForm()

    context = {'question_id':question.id, 'form':form}
    return render(request,'pybo/comment_form.html', context)

@login_required(login_url='common:login')
def comment_modify_que(request, comment_id):
    """
    pybo 질문에 대한 댓글 수정
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '수정권한이 없습니다.')
        return redirect('pybo:detail', question_id=comment.question.id)

    if request.method == 'POST':
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.modify_date = timezone.now()
            comment.save()
            #return redirect('pybo:detail',question_id=comment.question.id)
            return redirect('{}#comment_{}'.format(resolve_url('pybo:detail', question_id=comment.question.id), comment.id))
    else:
        form = CommentForm(instance=comment)
    context = {'question_id':comment.question.id, 'form':form}
    return render(request, 'pybo/comment_form.html', context)

@login_required(login_url='common:login')
def comment_delete_que(request, comment_id):
    """
    pybo 질문에 대한 댓글 삭제
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '삭제권한이 없습니다.')
    else:
        comment.delete()
    return redirect('pybo:detail', question_id=comment.question.id)

"""
pybo 답변에 대한 댓글 부분
"""

@login_required(login_url='common:login')
def comment_create_ans(request, answer_id):
    """
    pybo 답변에 대한 댓글 등록
    """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user #현재 로그인 User 모델의 객체
            comment.create_date = timezone.now()
            comment.answer = answer
            comment.save()
            #return redirect('pybo:detail', question_id=comment.answer.question.id)
            return redirect('{}#comment_{}'.format(resolve_url('pybo:detail', question_id=comment.answer.question.id), comment.id))
    else:
        form = CommentForm()

    context = {'question_id':answer.question.id, 'form':form}
    return render(request,'pybo/comment_form.html', context)

@login_required(login_url='common:login')
def comment_modify_ans(request, comment_id):
    """
    pybo 답변에 대한 댓글 수정
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '수정권한이 없습니다.')
        return redirect('pybo:detail', question_id=comment.answer.question.id)

    if request.method == 'POST':
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.modify_date = timezone.now()
            comment.save()
            #return redirect('pybo:detail',question_id=comment.answer.question.id)
            return redirect('{}#comment_{}'.format(resolve_url('pybo:detail', question_id=comment.answer.question.id), comment.id))
    else:
        form = CommentForm(instance=comment)
    context = {'question_id':comment.answer.question.id, 'form':form}
    return render(request, 'pybo/comment_form.html', context)

@login_required(login_url='common:login')
def comment_delete_ans(request, comment_id):
    """
    pybo 답변에 대한 댓글 삭제
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '삭제권한이 없습니다.')
    else:
        comment.delete()
    return redirect('pybo:detail', question_id=comment.answer.question.id)

pybo/views/question_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone

from ..forms import QuestionForm
from ..models import Question,Category

@login_required(login_url='common:login')
def question_create(request):
    """
    pybo 질문 등록
    """
    categorys = Category.objects.order_by('-id')

    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user  # 현재 로그인 User 모델의 객체
            question.create_date = timezone.now()
            question.save()
            #return redirect('pybo:index')
            return redirect('{}?ca={}'.format(resolve_url('pybo:index'),question.cate_id))
    else:
        form = QuestionForm()
    context = {'form':form, 'cate_list':categorys}
    return render(request, 'pybo/question_form.html', context)

@login_required(login_url='common:login')
def question_modify(request, question_id):
    """
    pybo 질문 수정
    """
    categorys = Category.objects.order_by('-id')
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '수정권한이 없습니다.')
        return redirect('pybo:detail', question_id=question.id)

    if request.method == 'POST':
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.modify_date = timezone.now()
            question.save()
            return redirect('pybo:detail',question_id=question.id)
    else:
        form = QuestionForm(instance=question)
    context = {'form':form, 'cate_list':categorys}
    return render(request, 'pybo/question_form.html', context)

@login_required(login_url='common:login')
def question_delete(request, question_id):
    """
    pybo 질문 삭제
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '삭제권한이 없습니다.')
        return redirect('pybo:detail', question_id=question.id)
    question.delete()
    return redirect('pybo:index')

pybo/views/vote_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect

from ..models import Question, Answer


@login_required(login_url='common:login')
def vote_question(request, question_id):
    """
    pybo 질문 추천 등록
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.user == question.author:
        messages.error(request, '본인이 작성한 글은 추천할 수 없습니다')
    else:
        question.voter.add(request.user)
    return redirect('pybo:detail', question_id=question.id)

@login_required(login_url='common:login')
def vote_answer(request, answer_id):
    """
    pybo 답변 추천 등록
    """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user == answer.author:
        messages.error(request, '본인이 작성한 답변은 추천할 수 없습니다')
    else:
        answer.voter.add(request.user)
    return redirect('pybo:detail', question_id=answer.question.id)

templates/pybo/answer_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <form method="post" class="post-form">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="content">답변내용</label>
            <textarea name="content" id="content" class="form-control"
                      rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <input type="submit" value="답변수정저장" class="btn btn-primary">
        <a href="{% url 'pybo:detail' answer.question_id %}" class="btn btn-primary">돌아가기</a>
    </form>
</div>
{% endblock %}

templates/pybo/comment_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <form method="post" class="post-form">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="content">댓글내용</label>
            <textarea name="content" id="content" class="form-control"
                      rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <input type="submit" value="저장하기" class="btn btn-primary">
        <a href="{% url 'pybo:detail' question_id %}" class="btn btn-primary">돌아가기</a>
    </form>
</div>
{% endblock %}

templates/pybo/question_detail(2020-0807).html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}
<div class="container my-3">
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
        {% for msg in messages %}
        <strong>{{ msg.tags }}</strong>
        <ul><li>{{ msg.message }}</li></ul>
        {% endfor %}
    </div>
    {% endif %}
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="row my-3">
        <div class="col-1"> <!-- 추천 영역 -->
            <div class="bg-light text-center p-3 border font-weight-bolder mb-1">{{question.voter.count}}</div>
            <a href="#" data-uri="{% url 'pybo:vote_question' question.id  %}"
               class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
        </div>
        <div class="col-11"> <!-- 질문 영역 -->

            <div class="card">
                <div class="card-body">
                    <div class="card-text">{{ question.content|mark }}</div>
                    <div class="d-flex justify-content-end">
                        {% if question.modify_date %}
                        <div class="badge badge-light p-2 text-left mx-3">
                            <div class="mb-2">modified at</div>
                            <div>{{ question.modify_date }}</div>
                        </div>
                        {% endif %}
                        <div class="badge badge-light p-2 text-left">
                            <div class="mb-2">{{ question.author.username }}</div>
                            <div>{{ question.create_date }}</div>
                        </div>
                    </div>
                    {% if request.user == question.author %}
                    <div class="my-3">
                        <a href="{% url 'pybo:question_modify' question.id %}" class="btn btn-sm btn-outline-secondary">수정</a>
                        <a href="#" class="delete btn btn-sm btn-outline-secondary" data-uri="{% url 'pybo:question_delete' question.id %}">삭제</a>
                    </div>
                    {% endif %}
                    <!-- 질문 댓글 //-->
                    {% if question.comment_set.count > 0 %}
                    <div class="mt-3">
                    {% for comment in question.comment_set.all %}
                        <a name="comment_{{ comment.id }}"></a>
                        <div class="comment py-2 text-muted">
                            <span style="white-space: pre-line;">{{ comment.content }}</span>
                            <span>
                                - {{ comment.author }}, {{ comment.create_date }}
                                {% if comment.modify_date %} (수정: {{ comment.modify_date }}) {% endif %}
                            </span>
                            {% if request.user == comment.author %}
                            <a href="{% url 'pybo:comment_modify_que' comment.id %}" class="small">수정</a> |
                            <a href="{% url 'pybo:comment_delete_que' comment.id %}" class="small">삭제</a>
                            {% endif %}
                        </div>
                    {% endfor %}
                    </div>
                    {% endif %}
                    <div>
                        <a href="{% url 'pybo:comment_create_que' question.id %}" class="small"><small>[댓글추가]</small></a>
                    </div>
                </div>
            </div>

        </div>
    </div>

    <!-- 답변 목록 //-->
    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all %}
    <a name="answer_{{ answer.id }}"></a>
    <div class="row my-3">
        <div class="col-1">  <!-- 추천영역 -->
            <div class="bg-light text-center p-3 border font-weight-bolder mb-1">{{ answer.voter.count }}</div>
            <a href="#" data-uri="{% url 'pybo:vote_answer' answer.id %}"
               class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
        </div>
        <div class="col-11"> <!-- 답변영역 -->

            <div class="card">
                <div class="card-body">
                    <div class="card-text">{{ answer.content|mark }}</div>
                    <div class="d-flex justify-content-end">
                        {% if answer.modify_date %}
                        <div class="badge badge-light p-2 text-left mx-3">
                            <div class="mb-2">modified at</div>
                            <div>{{ answer.modify_date }}</div>
                        </div>
                        {% endif %}
                        <div class="badge badge-light p-2 text-left">
                            <div class="mb-2">{{ answer.author.username }}</div>
                            <div>{{ answer.create_date }}</div>
                        </div>
                    </div>
                    {% if request.user == question.author %}
                    <div class="my-3">
                        <a href="{% url 'pybo:answer_modify' answer.id %}" class="btn btn-sm btn-outline-secondary">답변수정</a>
                        <a href="#" class="delete btn btn-sm btn-outline-secondary" data-uri="{% url 'pybo:answer_delete' answer.id %}">답변삭제</a>
                    </div>
                    {% endif %}
                    <!-- 답변 댓글 //-->
                    {% if answer.comment_set.count %}
                    <div class="mt-3">
                    {% for comment in answer.comment_set.all %}
                        <a name="comment_{{ comment.id }}"></a>
                        <div class="comment py-2 text-muted">
                            <span style="white-space: pre-line;">{{ comment.content }}</span>
                            <span>
                                - {{ comment.author }}, {{ comment.create_date }}
                                {% if comment.modify_date %} (수정: {{ comment.modify_date }}) {% endif %}
                            </span>
                            {% if request.user == comment.author %}
                            <a href="{% url 'pybo:comment_modify_ans' comment.id %}" class="small">수정</a> |
                            <a href="{% url 'pybo:comment_delete_ans' comment.id %}" class="small">삭제</a>
                            {% endif %}
                        </div>
                    {% endfor %}
                    </div>
                    {% endif %}
                    <div>
                        <a href="{% url 'pybo:comment_create_ans' answer.id %}" class="small"><small>[댓글추가]</small></a>
                    </div>
                </div>
            </div>

        </div>
    </div>
    {% endfor %}

    <!-- 답변 등록폼 //-->
    <form action="{% url 'pybo:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
                {% if field.errors %}
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            {% endif %}
        {% endfor %}
        </div>
        {% endif %}
        <div class="form-group">
            {% if user.is_authenticated %} <!-- 로그인 하지 않을 경우 답변 등록 못하게 처리(여러가지 가능) //-->
            <textarea name="content" id="content" class="form-control" rows="10"></textarea>
            {% endif %}
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary" id="answer_but">
        <a href="{%url 'pybo:index' %}" class="btn btn-primary">목록가기</a>
    </form>
</div>
{% endblock %}

{% block script %}
<script language="JavaScript1.2">
{% if not user.is_authenticated %}
document.getElementById("answer_but").addEventListener("click", function(){
   alert("먼저 로그인 하세요");
});
{% endif %}

$(document).ready(function(){
    $(".delete").on('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });

    $(".recommend").on('click', function() {
        if(confirm("정말로 추천하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });

});
</script>
{% endblock %}

templates/pybo/question_form.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'simplemde.min.css' %}">
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
           {% for field in form %}
              {% if field.errors %}
                 <strong>{{field.label}}</strong>
                 {{field.errors}}
              {% endif %}
           {% endfor %}
        </div>
        {% endif %}

        <div class="form-group col-3">
            <label for="subject">분류</label>
            <select class="form-control" name="cate" id="cate">
                <option value="">게시판 분류 선택</option>
                {% if cate_list %}
                {% for cate in cate_list %}
                <option value="{{ cate.id }}">{{ cate.cname }}</option>
                {% endfor %}
                {% endif %}
            </select>
        </div>

        <div class="form-group">
            <label for="subject">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="content">내용</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}
{% block script %}
<script src="{% static 'simplemde.min.js' %}"></script>
<script language="JavaScript1.2">
var simplemde = new SimpleMDE({ element: document.getElementById("content") });

$(document).ready(function(){
    $("#cate").val({{ form.cate.value|default_if_none:'' }});
});

</script>
{% endblock %}