common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('user_mod/', views.user_mod, name='user_mod'),
    path('pass_mod_p/', views.pass_mod_p, name='pass_mod_p'),
    path('pass_mod_req/', views.pass_mod_req, name='pass_mod_req'),
    path('user_info/', views.user_info, name='user_info'),
]

pybo/urls.py
from django.urls import path
from .views import base_views, question_views, answer_views, comment_views, vote_views

app_name = 'pybo'

urlpatterns = [
    #base_views.py
    path('', base_views.index, name='index'),
    path('<int:question_id>/', base_views.detail, name='detail'),

    #question_views.py
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),

    #answer_views.py
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),

    #comment_views.py
    path('comment/create/question/<int:question_id>/', comment_views.comment_create_que, name='comment_create_que'),
    path('comment/modify/question/<int:comment_id>/', comment_views.comment_modify_que, name='comment_modify_que'),
    path('comment/delete/question/<int:comment_id>/', comment_views.comment_delete_que, name='comment_delete_que'),
    path('comment/create/answer/<int:answer_id>/', comment_views.comment_create_ans, name='comment_create_ans'),
    path('comment/modify/answer/<int:comment_id>/', comment_views.comment_modify_ans, name='comment_modify_ans'),
    path('comment/delete/answer/<int:comment_id>/', comment_views.comment_delete_ans, name='comment_delete_ans'),

    #vote_views.py
    path('vote/question/<int:question_id>/', vote_views.vote_question, name='vote_question'),
    path('vote/answer/<int:answer_id>/', vote_views.vote_answer, name='vote_answer'),
]

common/models.py
from django.db import models

# Create your models here.

pybo/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

#게시글 카테고리
class Category(models.Model):
    cname = models.CharField(max_length=100)
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)

#게시글 질문하기
class Question(models.Model):
    cate = models.ForeignKey(Category, on_delete=models.DO_NOTHING)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question')
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_question')
    cnt = models.IntegerField(default=0)

    def __str__(self):
        return self.subject


#게시글 답변하기
class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_answer')
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_answer')

#댓글
class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    question = models.ForeignKey(Question, null=True, blank=True, on_delete=models.CASCADE)
    answer = models.ForeignKey(Answer, null=True, blank=True, on_delete=models.CASCADE)

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm,UserModel
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model  # helper 함수를 통해 모델 클래스 참고


class UserBasicForm(forms.ModelForm):
    username = forms.CharField(label="사용자ID")
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("email",)


class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "email")


class UserUpdateForm(UserChangeForm):
    email = forms.EmailField(label="이메일")
    password1 = forms.CharField(label='비밀번호', widget=forms.PasswordInput)

    class Meta:
        model = get_user_model()
        fields = ("username", "email")


"""
class PassUpdateForm(forms.ModelForm):
    password1 = forms.CharField(label='새 비밀번호', widget=forms.PasswordInput)
    password2 = forms.CharField(label='새 비밀번호 확인', widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ("username",)
"""

common/views.py
from django.contrib.auth import authenticate, login, logout, forms, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from common.forms import UserForm,UserUpdateForm,UserBasicForm
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth.models import User
from django.db.models import Q
from common.comm_mod import pass_rand,page_navi
from django.core.mail import EmailMessage

from pybo.models import Category,Question,Answer,Comment

def signup(request):
    """
    계정생성
    """
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request,user)
            return redirect('index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form':form})

@login_required
def user_mod(request):
    """
    계정수정
    """
    if request.method == "POST":
        form = UserUpdateForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save(commit=False)
            """
            비밀번호 체크하기
            """
            username = form.cleaned_data.get('username')
            raw_password = request.POST.get('password1')
            user = authenticate(username=username, password=raw_password)
            if user is not None:
                form.save()
                messages.info(request, '이메일이 수정 되었습니다.')
            else:
                #return HttpResponse("비밀번호가 틀렸습니다.")
                messages.error(request, '비밀번호가 틀렸습니다.')
    else:
        form = UserUpdateForm(instance=request.user)
    return render(request, 'common/user_mod.html', {'form':form})


@login_required
def pass_mod_p(request):
    """
    비밀번호 수정 처리
    """
    if request.method == "POST":
        form = forms.PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # 수정후 자동 로그인
            messages.success(request, '비밀번호가 변경 되어 다시 로그인 했습니다.')
            return redirect('common:pass_mod_p')
        else:
            messages.error(request,"비밀번호 수정 에러!")
    else:
        form = forms.PasswordChangeForm(request.user)
    return render(request, 'common/pass_mod_p.html', {'form': form})


def pass_mod_req(request):
    """
    비밀번호 분실 요청
    """
    if request.method == "POST":
        form = UserBasicForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            email = form.cleaned_data.get('email')
            member = User.objects.filter(Q(username=username),Q(email=email))
            if member:
                new_pass = pass_rand(8)
                member[0].set_password(new_pass) # 암호화
                member[0].save()

                subj = "안녕하세요. 파이보 입니다. "+username+" 회원님께서 요청하신 내용 입니다."
                cont = "요청하신 임시 비밀번호는 "+new_pass+" 입니다. 로그인 후에 꼭 변경해 주세요."
                smail = EmailMessage(
                    subj,
                    cont,
                    to=[email]
                )
                succ = smail.send()
                # 발송 에러남 : 구글 gmail stmp 이용 발송시 보안수준이 낮은 앱의 엑세스 허용 해야 함. https://myaccount.google.com/lesssecureapps

                if succ:
                    messages.info(request, '임시 비밀번호 정보를 가입하신 이메일주소로 발송 했습니다.')
                else:
                    messages.info(request, member[0].password+"  ,  "+new_pass)

                # 랜덤한 비밀번호 생성 (8자리 문자열), db 저장 , 이메일 발송 -> 결과 리턴 후 발송완료 메세지
                # messages.info(request, '가입하신 이메일을 발송 했습니다.')
            else:
                messages.error(request, '일치하는 사용자가 없습니다. 다시 확인해 주세요.')
            form = UserBasicForm()
    else:
        form = UserBasicForm()
    return render(request, 'common/pass_mod_req.html', {'form':form})

@login_required
def user_info(request):
    """
    사용자 정보
    """
    qpage = request.GET.get('qpage','1')
    apage = request.GET.get('apage','1')
    cpage = request.GET.get('cpage','1')

    #member = User.objects.filter(Q(username=request.user))
    member = User.objects.get(username=request.user)

    question_list = Question.objects.filter(author_id=request.user).order_by('-id')
    answer_list = Answer.objects.filter(author_id=request.user).order_by('-id')
    comment_list = Comment.objects.filter(author_id=request.user).order_by('-id')

    page_obj1 = page_navi(question_list, qpage, 2)
    page_obj2 = page_navi(answer_list, apage, 5)
    page_obj3 = page_navi(comment_list, cpage, 5)
    
    context = {'member':member,'question_list': page_obj1, 'answer_list': page_obj2, 'comment_list': page_obj3,
               'qpage': qpage, 'apage': apage, 'cpage': cpage}

    return render(request, 'common/user_info.html', context)

def page_not_found(request, exception):
    """
    404 Page not found
    """
    return render(request, 'common/404.html', {})

templates/common/login.html
{% extends 'base.html' %}
{% block content %}
{% load socialaccount %}
{% providers_media_js %}
<div class="container my-3">
    <div class="row">
        <div class="col-4">
            <h4>로그인</h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'common:signup' %}">계정을 만드세요</a></span>
        </div>
    </div>
    <div class="row">
        <div class="col-12 text-right"">
            <span>비밀번호를 잃어 버리셨으면 <a href="{% url 'common:pass_mod_req' %}">[임시비밀번호 요청 하세요]</a></span>
        </div>
    </div>
    <form method="post" class="post-form" action="{% url 'common:login' %}">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{next}}">
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password">사용자 비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
    <div class="row">
        <div class="col-12 text-left p-3">
            <span><a href="{% provider_login_url 'google' %}">[구글로그인]</a></span>
            <span><a href="{% provider_login_url 'naver' %}">[네이버로그인]</a></span>
        </div>
    </div>
</div>
{% endblock %}

templates/common/pass_mod_p.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <div class="row my-3">
        <div class="col-4">
            <h4>비밀번호 수정하기</h4>
        </div>
    </div>
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
        {% for msg in messages %}
        <strong>{{ msg.tags }}</strong>
        <ul><li>{{ msg.message }}</li></ul>
        {% endfor %}
    </div>
    {% endif %}
    <form method="post" class="post-form">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <table class="table">
        {{ form }}
        </table>

        <button type="submit" class="btn btn-primary">수정저장하기</button>
    </form>
</div>
{% endblock %}

templates/common/pass_mod_req.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <div class="row">
        <div class="col-4">
            <h4>비밀번호 분실 요청</h4>
        </div>
        <div class="col-8 text-right">
            <span>임의로 생성된 신규 비밀번호를 가입하신 이메일로 보내드립니다.</span>
        </div>
    </div>
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
        {% for msg in messages %}
        <strong>{{ msg.tags }}</strong>
        <ul><li>{{ msg.message }}</li></ul>
        {% endfor %}
    </div>
    {% endif %}
    <form method="post" class="post-form">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">확인</button>
    </form>
</div>
{% endblock %}

templates/common/signup.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <div class="row my-3">
        <div class="col-4">
            <h4>계정생성</h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'common:login' %}">로그인 하세요</a></span>
        </div>
    </div>
    <form method="post" class="post-form">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username">사용자이름</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">계정생성하기</button>
    </form>
</div>
{% endblock %}

templates/common/user_info.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}
<div class="container my-3">
    <h2 class="border-bottom py-2">프로필</h2>
    <div class="row my-3">
        <div class="col-12"> <!-- 정보영역 -->

            <div class="card">
                <div class="card-body">
                    <div class="card-text">
                        사용자 ID : {{ member.username }}
                    </div>
                    <div class="mt-3">
                        사용자 이메일 : {{ member.email }}
                    </div>

                    <div class="mt-3">
                        가입일 : {{ member.date_joined }}
                    </div>
                </div>
            </div>

        </div>
    </div>

    <!-- 나의 질문 //-->
    <div class="row justify-content-between my-3">
        <div class="col-3">나의 질문 (총 {{ question_list.paginator.count }} 개)</div>
        
        <table class="table">
            <thead>
            <tr class="thead-dark">
                <th>번호</th>
                <th>분류</th>
                <th>추천</th>
                <th style="width:50%">제목</th>
                <th>글쓴이</th>
                <th>작성일시</th>
            </tr>
            </thead>
            <tbody>
            {% if question_list %}
            {% for question in question_list %}
            <tr>
                <td>
                    <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                    {{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}
                </td>
                <td>
                    {{ question.cate.cname }}
                </td>
                <td>
                    {% if question.voter.all.count > 0 %}
                    <span class="badge badge-warning px-2 py-1">{{ question.voter.all.count }}</span>
                    {% endif %}
                </td>
                <td>
                    <a href="{% url 'pybo:detail' question.id %}">{{ question.subject }}</a>
                    {% if question.answer_set.count > 0 %}
                    <span class="text-danger small ml-2">[{{ question.answer_set.count }}]</span>
                    {% endif %}
                </td>
                <td>{{ question.author.username }}</td>
                <td>{{ question.create_date }}</td>
            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td colspan="4">질문이 없습니다.</td>
            </tr>
            {% endif %}
            </tbody>
        </table>    

        {% include "page_navi.html" with page_class='qpage-link' boardlist=question_list %}

    </div>

    <!-- 나의 답변 //-->
    <div class="row justify-content-between my-3">
        <div class="col-3">나의 답변 (총 {{ answer_list.paginator.count }} 개)</div>

        <table class="table">
            <thead>
            <tr class="thead-dark">
                <th>번호</th>
                <th>추천</th>
                <th style="width:50%">내용</th>
                <th>글쓴이</th>
                <th>작성일시</th>
            </tr>
            </thead>
            <tbody>
            {% if answer_list %}
            {% for answer in answer_list %}
            <tr>
                <td>
                    <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                    {{ answer_list.paginator.count|sub:answer_list.start_index|sub:forloop.counter0|add:1 }}
                </td>
                <td>
                    {% if answer.voter.all.count > 0 %}
                    <span class="badge badge-warning px-2 py-1">{{ answer.voter.all.count }}</span>
                    {% endif %}
                </td>
                <td>
                    <a href="{% url 'pybo:detail' answer.question_id %}">{{ answer.content | slice:":20" }}</a>
                    {% if answer.content|length > 20 %}
                    . . . . . .
                    {% endif %}
                    {% if answer.comment_set.count > 0 %}
                    <span class="text-danger small ml-2">[{{ answer.comment_set.count }}]</span>
                    {% endif %}
                </td>
                <td>{{ answer.author.username }}</td>
                <td>{{ answer.create_date }}</td>
            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td colspan="4">답변이 없습니다.</td>
            </tr>
            {% endif %}
            </tbody>
        </table>

        {% include "page_navi.html" with page_class='apage-link' boardlist=answer_list %}

    </div>

    <!-- 나의 댓글 //-->
    <div class="row justify-content-between my-3">
        <div class="col-3">나의 댓글 (총 {{ comment_list.paginator.count }} 개)</div>

        <table class="table">
            <thead>
            <tr class="thead-dark">
                <th>번호</th>
                <th>질문/답변</th>
                <th style="width:50%">내용</th>
                <th>글쓴이</th>
                <th>작성일시</th>
            </tr>
            </thead>
            <tbody>
            {% if comment_list %}
            {% for comment in comment_list %}
            <tr>
                <td>
                    <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                    {{ comment_list.paginator.count|sub:comment_list.start_index|sub:forloop.counter0|add:1 }}
                </td>
                <td>
                    {% if comment.question_id %}
                       질문
                    {% else %}
                       답변
                    {% endif %}
                </td>
                <td>
                    {% if comment.question_id %}
                        <a href="{% url 'pybo:detail' question_id=comment.question_id %}">
                    {% else %}
                        <a href="{% url 'pybo:detail' question_id=comment.answer.question_id %}">
                    {% endif %}
                    {{ comment.content | slice:":20" }}</a>
                    {% if comment.content|length > 20 %}
                    . . . . . .
                    {% endif %}
                </td>
                <td>{{ comment.author.username }}</td>
                <td>{{ comment.create_date }}</td>
            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td colspan="4">댓글이 없습니다.</td>
            </tr>
            {% endif %}
            </tbody>
        </table>

        {% include "page_navi.html" with page_class='cpage-link' boardlist=comment_list %}

    </div>

</div>
<form id="searchForm" method="get" action="{% url 'common:user_info' %}">
    <input type="hidden" id="qpage" name="qpage" value="{{ qpage }}">
    <input type="hidden" id="apage" name="apage" value="{{ apage }}">
    <input type="hidden" id="cpage" name="cpage" value="{{ cpage }}">
</form>
{% endblock %}

{% block script %}
<script language="JavaScript1.2">
$(document).ready(function(){

    $(".qpage-link").on('click', function() {
        $("#qpage").val($(this).data("page"));
        $("#searchForm").submit();
    });

    $(".apage-link").on('click', function() {
        $("#apage").val($(this).data("page"));
        $("#searchForm").submit();
    });

    $(".cpage-link").on('click', function() {
        $("#cpage").val($(this).data("page"));
        $("#searchForm").submit();
    });

});

</script>
{% endblock %}

templates/common/user_mod.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
        {% for msg in messages %}
        <strong>{{ msg.tags }}</strong>
        <ul><li>{{ msg.message }}</li></ul>
        {% endfor %}
    </div>
    {% endif %}
    <div class="row my-3">
        <div class="col-4">
            <h4>사용자 이메일 수정</h4>
        </div>
    </div>
    <form method="post" class="post-form">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username">사용자이름</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}" readonly>
        </div>
        <div class="form-group">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">정보수정하기</button>
    </form>
</div>
{% endblock %}