common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('user_mod/', views.user_mod, name='user_mod'),
    path('pass_mod_p/', views.pass_mod_p, name='pass_mod_p'),
    path('pass_mod_req/', views.pass_mod_req, name='pass_mod_req'),
    path('user_info/', views.user_info, name='user_info'),
]

pybo/urls.py
from django.urls import path
from .views import base_views, question_views, answer_views, comment_views, vote_views

app_name = 'pybo'

urlpatterns = [
    #base_views.py
    path('', base_views.index, name='index'),
    path('<int:question_id>/', base_views.detail, name='detail'),

    #question_views.py
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),

    #answer_views.py
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),

    #comment_views.py
    path('comment/create/question/<int:question_id>/', comment_views.comment_create_que, name='comment_create_que'),
    path('comment/modify/question/<int:comment_id>/', comment_views.comment_modify_que, name='comment_modify_que'),
    path('comment/delete/question/<int:comment_id>/', comment_views.comment_delete_que, name='comment_delete_que'),
    path('comment/create/answer/<int:answer_id>/', comment_views.comment_create_ans, name='comment_create_ans'),
    path('comment/modify/answer/<int:comment_id>/', comment_views.comment_modify_ans, name='comment_modify_ans'),
    path('comment/delete/answer/<int:comment_id>/', comment_views.comment_delete_ans, name='comment_delete_ans'),

    #vote_views.py
    path('vote/question/<int:question_id>/', vote_views.vote_question, name='vote_question'),
    path('vote/answer/<int:answer_id>/', vote_views.vote_answer, name='vote_answer'),
]

pybo/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.db.models import Q, Count
from ..models import Category,Question,Answer,Comment

import logging
logger = logging.getLogger('pybo')

def index(request):
    """
    pybo 질문 목록 출력
    """

    logger.info("INFO 레벨로 출력")

    #최근 답변 5개
    new_answer = Answer.objects.order_by('id')[:5]

    #최근 댓글 5개
    new_comment = Comment.objects.order_by('id')[:5]

    page = request.GET.get('page','1')
    kw = request.GET.get('kw','')
    so = request.GET.get('so', 'recent')
    ca = request.GET.get('ca', '')

    categorys = Category.objects.order_by('-id')

    if not ca:
        question_list = Question.objects.select_related('cate').filter(cate_id=1)
        ca = 1
    elif ca == 'all':
        question_list = Question.objects.select_related('cate')
    else:
        question_list =  Question.objects.select_related('cate').filter(cate_id=ca)

    if so == 'recommend':
        question_list = question_list.annotate(num_voter=Count('voter')).order_by('-num_voter','-id')
    elif so == 'popular':
        question_list = question_list.annotate(num_answer=Count('answer')).order_by('-num_answer','-id')
    else: #recent
        question_list = question_list.order_by('-id')

    if kw: #검색키워드
        question_list = question_list.filter(
            Q(subject__icontains=kw) |
            Q(content__icontains=kw) |
            Q(author__username__icontains=kw) |
            Q(answer__author__username__icontains=kw)
        ).distinct()

    import math

    paginator = Paginator(question_list,10)
    page_obj = paginator.get_page(page)
    page_obj.e_number = math.ceil(page_obj.paginator.count / page_obj.paginator.per_page)

    context = {'question_list': page_obj, 'page': page, 'kw': kw, 'so': so, 'ca':ca, 'cate_list':categorys,'new_answer':new_answer,'new_comment':new_comment}
    return render(request, 'pybo/question_list.html', context)

def detail(request, question_id):
    """
    pybo 질문 내용출력
    """
    page = request.GET.get('page', '1')
    so = request.GET.get('so', 'recent')

    question = get_object_or_404(Question, pk=question_id)

    # 조회수 증가
    view_cnt = 'view_count(%d)'%question.id
    if view_cnt not in request.session._session:
        request.session[view_cnt] = True
        question.cnt = question.cnt + 1
        question.save()

    if so == 'recommend':
        answer = Answer.objects.filter(question_id=question_id).annotate(num_voter=Count('voter')).order_by('-num_voter','-id')
    else: #recent
        answer = Answer.objects.filter(question_id=question_id).order_by('-id')

    import math

    paginator = Paginator(answer,3)
    page_obj = paginator.get_page(page)
    page_obj.e_number = math.ceil(page_obj.paginator.count / page_obj.paginator.per_page)

    context = {'question': question,'answer_list': page_obj, 'page': page, 'so': so}
    return render(request, 'pybo/question_detail.html', context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<title>파이보2</title>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>안녕 하이보~</title>
</head>
<body>
{% include "navbar.html" %}

{% block content %}
{% endblock %}

<script src="{% static 'jquery-3.5.1.min.js' %}"></script>
<script src="{% static 'bootstrap.min.js' %}"></script>
{% block script %}
{% endblock %}
</body>
</html>

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'pybo:index' %}">Pybo</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item ">
                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'common:user_info' %}">{{ user.username }}</a>
                {% endif %}
            </li>
            <li class="nav-item ">
                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'common:logout' %}">[로그아웃]</a>
                {% else %}
                <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                {% endif %}
            </li>
            <li class="nav-item ">
                {% if user.is_authenticated and user.socialaccount_set.count == 0 %}
                <a class="nav-link" href="{% url 'common:user_mod' %}">[이메일 수정]</a>
                {% endif %}
            </li>
            <li class="nav-item ">
                {% if user.is_authenticated and user.socialaccount_set.count == 0  %}
                <a class="nav-link" href="{% url 'common:pass_mod_p' %}">[비밀번호 변경]</a>
                {% endif %}
            </li>

            <li class="nav-item ">
                {% if user.is_authenticated and user.socialaccount_set.count > 0 %}
                    {{ user.socialaccount_set.all.0.provider }} 로그인중
                {% endif %}
            </li>
        </ul>
    </div>
</nav>
<!--
   {% for account in user.socialaccount_set.all %}

     {% comment %} show avatar from url {% endcomment %}
     <h2 style="text-transform:capitalize;">{{ account.provider }} account data</h2>

     <p><img width="50" height="50" src="{{ account.get_avatar_url }}"/></p>

     <p>UID: <a href="{{ account.extra_data.link }}">{{ account.uid }}</a></p>

     <p>Username: {{ account.extra_data.username }}</p>
      <p>First Name: {{ account.extra_data.first_name }}</p>
      <p>Last Name: {{ account.extra_data.last_name }}</p>

      <p>Dashboard Link:
      <a href="{{ account.extra_data.link }}">{{ account.extra_data.link }}</a></p>
      {% empty %}
      <p>you haven't any social account please</p>
    {% endfor %}
//-->

templates/page_navi.html
        <ul class="pagination justify-content-center">
            <li class="page-item"><a class="{{ page_class }} page-link" data-page="1" href="#">처음</a></li>

            {% if boardlist.has_previous %}
            <li class="page-item"><a class="{{ page_class }} page-link" data-page="{{ boardlist.previous_page_number }}" href="#">이전</a></li>
            {% else %}
            <li class="page-item disabled"><a class="{{ page_class }} page-link" tabindex="-1" aria-disabled="true" href="#">이전</a></li>
            {% endif %}

            {% for page_number in boardlist.paginator.page_range %}
            {% if page_number >= boardlist.number|add:-5 and page_number <= boardlist.number|add:5 %}
               {% if page_number == boardlist.number %}
                <li class="page-item active" aria-current="page"><a class="{{ page_class }} page-link" data-page="{{page_number}}" href="#">{{page_number}}</a></li>
               {% else %}
                <li class="page-item"><a class="{{ page_class }} page-link" data-page="{{page_number}}" href="#">{{page_number}}</a></li>
               {% endif %}
            {% endif %}
            {% endfor %}

            {% if boardlist.has_next %}
            <li class="page-item"><a class="{{ page_class }} page-link" data-page="{{ boardlist.next_page_number }}" href="#">다음</a></li>
            {% else %}
            <li class="page-item disabled"><a class="{{ page_class }} page-link" tabindex="-1" aria-disabled="true" href="#">다음</a></li>
            {% endif %}
            <li class="page-item"><a class="{{ page_class }} page-link" data-page="{{ boardlist.e_number }}" href="#">끝</a></li>
        </ul>